PATCH http://localhost:3000/posts
Content-Type: application/json

{
    "id": 8,
    "title": "What's new in nestjs with typescript",
    "postType": "post",
    "slug": "whats-new-in-nestjs-2",
    "status": "draft",
    "content": "Nestjs has so many features that can make programming a lot easier for you",
    "schemas": "{\r\n \"@context\": \"https:\/\/schemas.org\",\r\n \"@type\": \"Person\"\r\n }",
    "featuredImageUrl": "http://localhost.com/assets/featured.png",
    "publishOn": "2024-10-29T00:00:00Z",
    "metaOptions": {
        "metaValue": "{\"sidebarEnabled\": true, \"footerActive\": true}"
    },
    "authorId": 1,
    "tags": [1, 3]

}