POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjcsImlhdCI6MTczNDMxNzg0NywiZXhwIjoxNzM0NDA0MjQ3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.2pQ3SHPcLWdorIIoMt48qp-w_SN7dlJthMs8C45F8ak"
}